language: php

matrix:
  fast_finish: true
  include:
  - php: 5.5
    env: LARAVEL_VERSION=5.0
  - php: 5.5
    env: LARAVEL_VERSION=5.1
  - php: 5.6
    env: LARAVEL_VERSION=5.0
  - php: 5.6
    env: LARAVEL_VERSION=5.1
  - php: 5.6
    env: LARAVEL_VERSION=5.2
  - php: 7
    env: LARAVEL_VERSION=5.0
  - php: 7
    env: LARAVEL_VERSION=5.1
  - php: 7
    env: LARAVEL_VERSION=5.2

  allow_failures:
  - php: 5.4
    env: LARAVEL_VERSION=5.0
  - php: 5.5
    env: LARAVEL_VERSION=5.0
  - php: 5.6
    env: LARAVEL_VERSION=5.0
  - php: 7
    env: LARAVEL_VERSION=5.0

before_install:
  - composer self-update
  - composer create-project laravel/laravel:$LARAVEL_VERSION
  - cd ./laravel
  - composer require padosoft/test
  - composer require padosoft/laravel-test
  #- composer config repositories.padosoft git https://github.com/@@@vendor/@@@package_name
  - composer require @@@vendor/@@@package_name dev-master
  - if [[ $LARAVEL_VERSION == '5.0' ]]; then composer require mockery/mockery; fi
  - chmod 777 -R ./
  - ./vendor/padosoft/laravel-composer-security/tests/config/sedCommand.sh
  - composer update
  - ./vendor/padosoft/laravel-composer-security/tests/config/sedCommandProvider.sh
  - rm ./.env
  - cp ./vendor/@@@vendor/@@@package_name/tests/config/.env.dist ./.env
  - php artisan vendor:publish
  - rvm 1.9.3 do gem install mime-types -v 2.6.2
  - gem install mailcatcher
  - mailcatcher

script:
  - vendor/bin/phpunit --configuration ./vendor/@@@vendor/@@@package_name/phpunit.xml.dist --testsuite Package --coverage-text --coverage-clover=coverage.clover

after_script:
notifications:
  slack:
    secure: lWDqhYcJ7n3I1lPsuUPjfUpZhVKMFe+wzyhsd1VMPgwB42xRqpjVNE1OOBKMXs0Htc3SHoE6WCpjfqr3CHHshhnPZo8Go0buInzHPSOOuQf8m+cyjVfYbIBzlQlyxthwOgEJeBxzON+fprm1X4f/bTtpPlWMo9ESG3DDVU2yQkQE3Bi0k2Sj+VP7VNyQtX/Ua3aRtBSxu5H0H54L6sHKXWCEPUkxCC/fJLbHCOTMnLmrEoITCRXydBladvtRP1Na6NFcyPwh5tViNmqvQPP3JBevIjgvPUwuz3pTuDBLW6jd+N9p603dBX2uIyttlBSjAF4FP6i18594VfQ2tJpAqKRELrHwHt3M3MpIbulcYZAnrz5WJf7M+HsER4TGNkkw+zuuBTHd+ImdBgQxxf8Qojy/O39RpGAZXxuBC8kJhWUpBl5noTf9aCxhOLUNpMvBF+67mHUQW3daqXpciDJlEIrLco6HhhyCkpvq0+RJ8/fL7B7mTik9N8mjRY2mkwQ6ytGhS4AVc6ICcFS4lC8FJFznG6nAFohOdayCGbGDzO2phKiXshl2zYbunkIALDYwxMRs5h64wOTfIoYvod1SiMOWbsE3J67BFg8tivRZ0/81L1VIGue4aJ10Ur0934ag4gAoMfIIJH1a2ASkF1tDIGMFW4RKP+qIjtuGVpikmLE=

  #- wget https://scrutinizer-ci.com/ocular.phar
  #- if [[ $TRAVIS_PHP_VERSION != '7.0' ]]; then php ocular.phar code-coverage:upload --access-token="93bdd4aee7a5446ac53fe372f1526b6a3d8af949ec675ab1963ca12398a4eebd" --format=php-clover coverage.clover; fi
