language: php
matrix:
  fast_finish: true
  include:
  - php: 7
    env: LARAVEL_VERSION=5.2
  allow_failures:
  - php: 7
    env: LARAVEL_VERSION=5.0
before_install:
- composer self-update
- composer create-project laravel/laravel:$LARAVEL_VERSION
- cd ./laravel
- composer require padosoft/test
- composer require padosoft/laravel-test
- composer require @@@vendor/@@@package_name dev-master
- if [[ $LARAVEL_VERSION == '5.0' ]]; then composer require mockery/mockery; fi
- chmod 777 -R ./
- "./vendor/padosoft/laravel-composer-security/tests/config/sedCommand.sh"
- composer update
- "./vendor/padosoft/laravel-composer-security/tests/config/sedCommandProvider.sh"
- rm ./.env
- cp ./vendor/@@@vendor/@@@package_name/tests/config/.env.dist ./.env
- php artisan vendor:publish
- rvm 1.9.3 do gem install mime-types -v 2.6.2
- gem install mailcatcher
- mailcatcher
script:
- vendor/bin/phpunit --configuration ./vendor/b2msrl/test-travis21/phpunit.xml.dist
  --testsuite Package --coverage-text --coverage-clover=coverage.clover
after_script:
  - git clone git@github.com:vaddy/vaddy-api-ruby.git && rvm use 2.1.0 && cd ./vaddy-api-ruby/ && ruby vaddy.rb
notifications:
   email:
      - travis@b2m-group.mailclark.ai
      - alessandro.manneschi@gmail.com