language: php
matrix:
  fast_finish: true
  include:
  - php: 5.5
    env: LARAVEL_VERSION=5.0
  - php: 5.5
    env: LARAVEL_VERSION=5.1
  - php: 5.6
    env: LARAVEL_VERSION=5.0
  - php: 5.6
    env: LARAVEL_VERSION=5.1
  - php: 5.6
    env: LARAVEL_VERSION=5.2
  - php: 7
    env: LARAVEL_VERSION=5.0
  - php: 7
    env: LARAVEL_VERSION=5.1
  - php: 7
    env: LARAVEL_VERSION=5.2
  allow_failures:
  - php: 5.4
    env: LARAVEL_VERSION=5.0
  - php: 5.5
    env: LARAVEL_VERSION=5.0
  - php: 5.6
    env: LARAVEL_VERSION=5.0
  - php: 7
    env: LARAVEL_VERSION=5.0
before_install:
- composer self-update
- composer create-project laravel/laravel:$LARAVEL_VERSION
- cd ./laravel
- composer require padosoft/test
- composer require padosoft/laravel-test
- composer require @@@vendor/@@@package_name dev-master
- if [[ $LARAVEL_VERSION == '5.0' ]]; then composer require mockery/mockery; fi
- chmod 777 -R ./
- "./vendor/padosoft/laravel-composer-security/tests/config/sedCommand.sh"
- composer update
- "./vendor/padosoft/laravel-composer-security/tests/config/sedCommandProvider.sh"
- rm ./.env
- cp ./vendor/@@@vendor/@@@package_name/tests/config/.env.dist ./.env
- php artisan vendor:publish
- rvm 1.9.3 do gem install mime-types -v 2.6.2
- gem install mailcatcher
- mailcatcher
script:
- vendor/bin/phpunit --configuration ./vendor/@@@vendor/@@@package_name/phpunit.xml.dist
  --testsuite Package --coverage-text --coverage-clover=coverage.clover
after_script: 
notifications:
  slack:
    secure: Eq7TLy8wPb2HM2NlsL+ItN1FYlnL4mYl4iaD8SoDdGXeKF+omKVCKrssAyDqnFLDXJLu+/nm6F4qv/0PlCx9K96DY/28qyQYsUxMUo6bjBkNpUUEszr1KiTeU50BBPw1T+x6cCe2KVFHfrEHzT+iXE4a3aZ8MCtbj6giJlyLY+rIYRVbfDRGJYTvg8FC/WJ2cbHQJ7V/lHk9yj94VSyTYfMJ7B1/1vJnYudln0KT9UWw8tIDyqjbjpyyxLuTyTiecXV28HHGF6QpbseSZynSlJqMrhmrtKAII2NTZldTJHYUHyGLsTSDyOYuBqg34tLOBQ7u2z2d9EB1KoH4HTo/KgITKsTxGFCgX4SbD/9Y7h4ikN5DD/Z58f98HFfFV59yfrqwkOSdpflVKrrD3BLldoojDXmBhtlPTA3mky6qsYalQ4KnobOi2bQBZlwsFN47RTbHzOYZZVxRnWJBh111zRjMuTaYJFGerqn4tvbbo+2VdPzVaYoFm1Y1RO08vlb1fo4f6tCnZQDPIlube1n60voIB942JQFIKfCM7BijSq8ezoUpioY+Fi4myvpZ3W/49xGn9W/4FeLLcnNhkWx1MCENAdpMSh3A3Qz7kVO0VkkqOu3OmzQ8AwXf1CSVloSwBnBL/p9RKE9LDUnA8eM8j/7LedA58iHE0ZQEoCsiOG4=
